cmake_minimum_required(VERSION 3.20)
project(OpenShapeMatchPackageConsumer LANGUAGES CXX)

find_package(OpenShapeMatch CONFIG REQUIRED)

add_executable(openshape_package_consumer main.cpp)
target_link_libraries(openshape_package_consumer PRIVATE openshape::OpenShapeMatch)
target_compile_features(openshape_package_consumer PRIVATE cxx_std_17)
